export const authorsData = [
  {
    author_name: "Hugh Millie-Yate",
    university: "University of Amsterdam",
    date_of_birth: "1964-08-20",
    h_index: 5,
    gender: "m",
  },
  {
    author_name: "Enise Unique",
    university: "Utrecht University",
    date_of_birth: "1995-07-31 ",
    h_index: 6,
    gender: "f",
    mentor: 1,
  },
  {
    author_name: "Sue Shei",
    university: "Leiden University",
    date_of_birth: "1995-12-14",
    h_index: 2,
    gender: "f",
    mentor: 1,
  },
  {
    author_name: "Alan Fresco",
    university: "Maastricht University",
    date_of_birth: "1984-05-05",
    h_index: 15,
    gender: "m",
    mentor: 1,
  },
  {
    author_name: "Fleece Marigold",
    university: "Maastricht University",
    date_of_birth: "1963-04-12",
    h_index: 30,
    gender: "f",
  },
  {
    author_name: "Desmond Eagle",
    university: "Erasmus University Rotterdam",
    date_of_birth: "1995-08-29",
    h_index: 3,
    gender: "m",
    mentor: 5,
  },
  {
    author_name: "Parsley Montana",
    university: "Tilburg University",
    date_of_birth: "1983-08-16",
    h_index: 22,
    gender: "m",
    mentor: 5,
  },
  {
    author_name: "Hilary Ouse",
    university: "Utrecht University",
    date_of_birth: "1964-03-20",
    h_index: 42,
    gender: "f",
    mentor: 5,
  },
  {
    author_name: "Justin Case",
    university: "University of Twente",
    date_of_birth: "1971-04-26",
    h_index: 38,
    gender: "m",
    mentor: 8,
  },
  {
    author_name: "Spruce Springclean",
    university: "University of Twente",
    date_of_birth: "1986-02-16",
    h_index: 34,
    gender: "m",
    mentor: 7,
  },
  {
    author_name: "Avi Cabrera",
    university: "University of Twente",
    date_of_birth: "1995-07-30",
    h_index: 6,
    gender: "f",
    mentor: 10,
  },
  {
    author_name: "Honey Singh",
    university: "Erasmus University Rotterdam",
    date_of_birth: "1967-12-24",
    h_index: 45,
    gender: "f",
    mentor: 3,
  },
  {
    author_name: "Angela Shyla",
    university: "Radboud University Nijmegen",
    date_of_birth: "1972-06-14",
    h_index: 29,
    gender: "f",
    mentor: 12,
  },
  {
    author_name: "Elyas Erickson",
    university: "Erasmus University Rotterdam",
    date_of_birth: "1979-01-02",
    h_index: 36,
    gender: "m",
    mentor: 12,
  },
  {
    author_name: "Anne-Marie Grimes",
    university: "Radboud University Nijmegen",
    date_of_birth: "1980-08-20",
    h_index: 33,
    gender: "f",
    mentor: 13,
  },
];
