export const researchPapersData = [
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-09-12",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-03-12",
    author: 5,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2021-05-10",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-05-24",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2019-06-07",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2017-01-12",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2017-07-16",
    author: 5,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2017-08-16",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-04-07",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2016-06-01",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2017-01-27",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-02-12",
    author: 5,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2016-01-02",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-07-13",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2020-07-12",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2021-11-28",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-03-31",
    author: 5,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-05-20",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2016-03-12",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2021-04-05",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-04-29",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-08-13",
    author: 5,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-11-08",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2021-03-06",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2015-10-09",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2019-06-15",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2020-05-03",
    author: 5,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-08-02",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2018-09-17",
    author: 2,
  },
  {
    paper_title: "rPaper",
    conference: "Amsterdam conference",
    publish_date: "2021-11-11",
    author: 2,
  },
];
