export const researchPapersData = [
  {
    paper_title: "Research About A",
    conference: "1. International Conference",
    publish_date: "2018-09-12",
    author: 2,
  },
  {
    paper_title: "Research About B",
    conference: "2. International Conference",
    publish_date: "2015-03-12",
    author: 1,
  },
  {
    paper_title: "Research About C",
    conference: "3. International Conference",
    publish_date: "2021-05-10",
    author: 2,
  },
  {
    paper_title: "Research About D",
    conference: "4. International Conference",
    publish_date: "2018-05-24",
    author: 3,
  },
  {
    paper_title: "Research About E",
    conference: "5. International Conference",
    publish_date: "2019-06-07",
    author: 4,
  },
  {
    paper_title: "Research About F",
    conference: "6. International Conference",
    publish_date: "2017-01-12",
    author: 5,
  },
  {
    paper_title: "Research About G",
    conference: "7. International Conference",
    publish_date: "2017-07-16",
    author: 5,
  },
  {
    paper_title: "Research About H",
    conference: "8. International Conference",
    publish_date: "2017-08-16",
    author: 7,
  },
  {
    paper_title: "Research About I",
    conference: "9. International Conference",
    publish_date: "2018-04-07",
    author: 8,
  },
  {
    paper_title: "Research About J",
    conference: "10. International Conference",
    publish_date: "2016-06-01",
    author: 7,
  },
  {
    paper_title: "Research About K",
    conference: "11. International Conference",
    publish_date: "2017-01-27",
    author: 8,
  },
  {
    paper_title: "Research About L",
    conference: "12. International Conference",
    publish_date: "2015-02-12",
    author: 10,
  },
  {
    paper_title: "Research About M",
    conference: "13. International Conference",
    publish_date: "2016-01-02",
    author: 10,
  },
  {
    paper_title: "Research About N",
    conference: "14. International Conference",
    publish_date: "2015-07-13",
    author: 10,
  },
  {
    paper_title: "Research About O",
    conference: "15. International Conference",
    publish_date: "2020-07-12",
    author: 11,
  },
  {
    paper_title: "Research About P",
    conference: "16. International Conference",
    publish_date: "2021-11-28",
    author: 12,
  },
  {
    paper_title: "Research About Q",
    conference: "17. International Conference",
    publish_date: "2018-03-31",
    author: 13,
  },
  {
    paper_title: "Research About R",
    conference: "18. International Conference",
    publish_date: "2015-05-20",
    author: 13,
  },
  {
    paper_title: "Research About S",
    conference: "19. International Conference",
    publish_date: "2016-03-12",
    author: 1,
  },
  {
    paper_title: "Research About T",
    conference: "20. International Conference",
    publish_date: "2021-04-05",
    author: 2,
  },
  {
    paper_title: "Research About U",
    conference: "21. International Conference",
    publish_date: "2015-04-29",
    author: 5,
  },
  {
    paper_title: "Research About V",
    conference: "22. International Conference",
    publish_date: "2015-08-13",
    author: 3,
  },
  {
    paper_title: "Research About Y",
    conference: "23. International Conference",
    publish_date: "2018-11-08",
    author: 5,
  },
  {
    paper_title: "Research About Z",
    conference: "24. International Conference",
    publish_date: "2021-03-06",
    author: 12,
  },
  {
    paper_title: "Research About ABC",
    conference: "25. International Conference",
    publish_date: "2015-10-09",
    author: 14,
  },
  {
    paper_title: "Research About BCD",
    conference: "26. International Conference",
    publish_date: "2019-06-15",
    author: 12,
  },
  {
    paper_title: "Research About DEF",
    conference: "27. International Conference",
    publish_date: "2020-05-03",
    author: 11,
  },
  {
    paper_title: "Research About FGH",
    conference: "28. International Conference",
    publish_date: "2018-08-02",
    author: 8,
  },
  {
    paper_title: "Research About HIJ",
    conference: "29. International Conference",
    publish_date: "2018-09-17",
    author: 8,
  },
  {
    paper_title: "Research About IJK",
    conference: "30. International Conference",
    publish_date: "2021-11-11",
    author: 5,
  },
];
